allowBuilds:
  core-js: true
minimumReleaseAgeExclude:
  - "@iconify/json@2.2.517"
shellEmulator: true

trustPolicy: no-downgrade

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - core-js
  - unrs-resolver
